create table public.expenses (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  image_url text not null,
  total_price text null,
  taxes text null,
  constraint expenses_pkey primary key (id)
) TABLESPACE pg_default;

create trigger expenses_trigger
after INSERT
or
update OF image_url on expenses for EACH row when (new.image_url is not null)
execute FUNCTION llm.call (
  'Extract the total price and taxes value from the image {image_url}',
  'total_price',
  'taxes'
);