create table public.user_reviews (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default gen_random_uuid (),
  user_review_og text not null,
  user_review_es text null,
  user_review_zh text null,
  emotion text null,
  full_name text null,
  user_background text null,
  attached_image_url text null,
  image_description text null,
  constraint user_reviews_pkey primary key (id)
);